using System.Reflection;
// Assembly metadata is maintained manually; retain the Windows contract normally
// generated by the SDK for net8.0-windows so platform analysis sees it.
[assembly: System.Runtime.Versioning.SupportedOSPlatform("windows7.0")]
[assembly: AssemblyTitle("Alchemist Reaction Timer")]
[assembly: AssemblyDescription("Dungeon Helper Reaction Spike timer")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: System.Runtime.Versioning.TargetFramework(".NETCoreApp,Version=v8.0", FrameworkDisplayName = ".NET 8.0")]

